# Generated by Django 5.1 on 2025-04-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_comments_bids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bids',
            new_name='bid',
        ),
        migrations.RenameModel(
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
