# Generated by Django 5.1 on 2026-04-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='listing_images/default.jpg', null=True, upload_to='listing_images/'),
        ),
    ]
