# Generated by Django 5.1 on 2026-04-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('ELEC', 'Electronics'), ('FASH', 'Fashion'), ('HOME', 'Home & Garden'), ('TOYS', 'Toys & Hobbies'), ('OTHR', 'Other')], default='OTHR', max_length=4),
        ),
    ]
