# Generated by Django 5.1 on 2026-04-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='highest_bidder',
        ),
    ]
