# Generated by Django 5.1 on 2026-04-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_highest_bidder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bid',
            new_name='starting_bid',
        ),
    ]
